# Generated by Django 5.2.5 on 2025-08-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        max_length=500, verbose_name="Texto de la Pregunta"
                    ),
                ),
                ("option_a", models.CharField(max_length=200, verbose_name="Opción A")),
                ("option_b", models.CharField(max_length=200, verbose_name="Opción B")),
                ("option_c", models.CharField(max_length=200, verbose_name="Opción C")),
                ("option_d", models.CharField(max_length=200, verbose_name="Opción D")),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[
                            ("A", "Opción A"),
                            ("B", "Opción B"),
                            ("C", "Opción C"),
                            ("D", "Opción D"),
                        ],
                        max_length=1,
                        verbose_name="Respuesta Correcta",
                    ),
                ),
                (
                    "prize_level",
                    models.IntegerField(
                        default=100, verbose_name="Nivel de Premio ($)"
                    ),
                ),
            ],
        ),
    ]
